const express = require('express');
const router = express.Router();
const hodController = require('../controllers/hodController');
const auth = require('../middleware/auth');

router.get('/faculties', auth(['HOD']), hodController.getFaculties);
router.get('/faculties/course/:courseId', auth(['HOD']), hodController.getFacultiesByCourse);
router.get('/faculties/department', auth(['HOD']), hodController.getFacultiesByDepartment);
router.post('/assign-course', auth(['HOD']), hodController.assignCourse);
router.post('/deallocate-course', auth(['HOD']), hodController.deallocateCourse);
router.post('/appoint-coordinator', auth(['HOD']), hodController.appointCoordinator);
router.post('/create-assessment', auth(['HOD']), hodController.createAssessment);
router.get('/review-assessment/:assessmentId/faculty/:facultyId', auth(['HOD']), hodController.reviewAssessment);
router.post('/create-course', auth(['HOD']), hodController.createCourse);
router.post('/activate-course', auth(['HOD']), hodController.activateCourse);
router.get('/catalog-courses', auth(['HOD']), hodController.getCatalogCourses);
router.get('/courses', auth(['HOD']), hodController.getCoursesByDepartment);
router.post('/approve-assessment/:assessmentId/faculty/:facultyId/set/:setName', auth(['HOD', 'CourseCoordinator', 'Faculty']), hodController.approveAssessment);
router.get('/download-assessment-questions/:courseId/:assessmentId', auth(['HOD']), hodController.downloadAssessmentQuestions);
router.get('/download-course-questions/:courseId', auth(['HOD']), hodController.downloadCourseQuestions);
router.get('/faculties/:facultyId/courses', auth(['HOD']), hodController.getCoursesByFaculty);
router.get('/get-sets/:facultyId/:assessmentId', auth(['HOD', 'CourseCoordinator', 'Faculty']), hodController.getSetsByFaculty);
router.delete('/delete-question/:questionId', auth(['HOD', 'CourseCoordinator', 'Faculty']), hodController.deleteQuestionByHOD);
router.put('/edit-question/:questionId', auth(['HOD', 'CourseCoordinator', 'Faculty']), hodController.editQuestionByHOD);
router.get('/pending-assessment-sets', auth(['HOD', 'CourseCoordinator', 'Faculty']), hodController.getPendingAssessmentSets);
router.delete('/course/:courseId', auth(['HOD']), hodController.deleteCourse);
router.get('/assessments/course/:courseId', auth(['HOD']), hodController.getAssessmentsByCourse);
router.put('/assessment/:assessmentId', auth(['HOD']), hodController.editAssessment);
router.delete('/assessment/:assessmentId', auth(['HOD']), hodController.deleteAssessment);
router.get('/download-questions', auth(['HOD']), hodController.downloadQuestions);
router.get('/master-filter', auth(['HOD']), hodController.masterFilterQuestions);
router.get('/stats', auth(['HOD']), hodController.getDashboardStats);
module.exports = router;
